- name: Install software packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - automake
    - autoconf
    - curl
    - flatpak
    - fzf
    - ncurses-devel
    - openssl
    - openssl-devel
    - ripgrep
    - tmux
    - xclip

