- name: Install software packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - autoconf
    - automake
    - aws
    - awscli
    - cmake
    - curl
    - flatpak
    - fzf
    - gcc
    - gcc-c++
    - htop
    - make
    - ncurses-devel
    - openssl
    - openssl-devel
    - postgresql
    - postgresql-server
    - postgresql-contrib
    - libpq-devel
    - readline-devel
    - redis
    - ripgrep
    - tmux
    - xclip
    - zlib-devel
  when: ansible_distribution == "Fedora"

