- name: Install software packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - automake
    - autoconf
    - curl
    - flatpak
    - fzf
    - ncurses-devel
    - openssl
    - openssl-devel
    - ripgrep
    - tmux
    - xclip

- name: asdf - install
  become_user: lance
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    version: v0.8.0
    dest: /home/lance/.asdf
    clone: yes
    force: no
