# Run before all other tasks
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

    - name: pre-run | update package cache
      tags: always
      command: dnf clean expire-cache
      changed_when: False
      when: ansible_distribution in ["Fedora"]

# Run roles
- hosts: localhost
  become: true
  roles:
    - common
    - workstation-dev

# # Run roles
# - hosts: all
#   tags: base
#   become: true
#   roles:
#     - base

# - hosts: workstation
#   tags: workstation
#   become: true
#   roles:
#     - workstation

# - hosts: server
#   tags: server
#   become: true
#   roles:
#     - server

# Clean up after run
- hosts: all
  become: true
  tasks:
    - name: clean up package cache
      tags: always
      apt:
        autoclean: yes
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

    - name: autoremove package cache
      tags: always
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    
    - name: clean up post install
      tags: always
      command: dnf clean all
      when: ansible_distribution in ["Fedora"]

    - name: autoremove
      tags: always
      dnf:
        autoremove: yes
      when: ansible_distribution in ["Fedora"]
