---
- name: Docker > add repository
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution == "Fedora"

- name: Docker > install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_distribution == "Fedora"
