- name: install rcm on macOS
  homebrew:
    name: rcm
    state: latest
  when: ansible_distribution == "MacOX"

- name: install rcm on Fedora
  become: yes
  dnf:
    name: rcm
    state: latest
  when: ansible_distribution == "Fedora"

- name: Where did those files go
  become: yes
  become_user: lance
  debug:
    msg: "Adding files to ${HOME}/.dotfiles"

- name: clone dotfiles
  become: yes
  become_user: lance 
  git:
    repo: https://github.com/lancejjohnson/dotfiles
    clone: yes
    dest: "${HOME}/.dotfiles"
    force: no

- name: configure rcup
  become: yes
  become_user: lance
  file:
    src: "${HOME}/.dotfiles/rcrc"
    dest: "${HOME}/.rcrc"
    state: link

- name: link dotfiles
  become: yes
  become_user: lance
  command: rcup -f -d "${HOME}/.dotfiles"

