---
# - name: Install fonts using brew bundle
#     command: brew bundle --file="{{ ansible_env.HOME }}/.dotfiles/Fontfile"
#   when: ansible_os_family == "Darwin"

- name: Install fonts (Fedora)
  become: yes
  ansible.builtin.dnf:
    name: "{{ item }}"
  loop:
    - fira-code-fonts
    - mozilla-fira-fonts-common
    - mozilla-fira-mono-fonts
    - mozilla-fira-sans-fonts
    - google-roboto-condensed-fonts
    - google-roboto-fonts
    - google-roboto-mono-fonts
    - google-roboto-slab-fonts
  when: ansible_distribution == "Fedora"

- name: Install Hack font (Fedora)
  block:
    - name: Download Hack font
      get_url:
        url: https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip
        dest: /tmp

    - name: Unzip Hack font
      unarchive:
        src: /tmp/Hack-v3.003-ttf.zip
        dest: /tmp

    - name: Move Hack font files
      copy:
        src: "/tmp/ttf/{{ item }}"
        dest: "/usr/share/fonts/{{ item }}"
      loop:
        - Hack-Bold.ttf
        - Hack-BoldItalic.ttf
        - Hack-Italic.ttf
        - Hack-Regular.ttf

  when: ansible_distribution == "Fedora"


