---
- name: Install software packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - autoconf
    - automake
    - aws
    - awscli
    - clang
    - cmake
    - curl
    - flatpak
    - fzf
    - gcc
    - gcc-c++
    - glib2-devel
    - htop
    - inkscape
    - libpq-devel
    - make
    - meld
    - meson
    - ncurses-devel
    - openssl
    - openssl-devel
    - optipng
    - postgresql
    - postgresql-contrib
    - postgresql-server
    - ranger
    - readline-devel
    - redis
    - ripgrep
    - sassc
    - shared-mime-info
    - tmux
    - xclip
    - zlib-devel
  when: ansible_distribution == "Fedora"

- name: Install system packages
  command: brew bundle --file="{{ ansible_env.HOME }}/.dotfiles/Brewfile"
  when: ansible_os_family == "Darwin"
