---
- name: 1Password
  when: ansible_distribution == "Fedora"
  block:
    - name: 1Password - rpm key
      become: yes
      ansible.builtin.rpm_key:
        state: present
        key: https://downloads.1password.com/linux/keys/1password.asc
  
    - name: 1Password - yum repo
      become: yes
      shell: 'echo -e "[1password]\nname=1Password\nbaseurl=https://downloads.1password.com/linux/rpm\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc" > /etc/yum.repos.d/1password.repo'

    - name: 1Password - install
      become: yes
      ansible.builtin.dnf:
        name: 1password
        state: latest