- name: Install software packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - autoconf
    - automake
    - curl
    - flatpak
    - fzf
    - gcc
    - gcc-c++
    - htop
    - make
    - ncurses-devel
    - openssl
    - openssl-devel
    - ripgrep
    - tmux
    - xclip
    - zlib-devel
  when: ansible_distribution == "Fedora"
