- name: Install software packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - automake
    - autoconf
    - flatpak
    - fzf
    - neovim
    - ncurses-devel
    - openssl
    - openssl-devel
    - python3-neovim
    - ripgrep
    - tmux
    - xclip

- name: Install minpac for neovim
  ansible.builtin.git:
    repo: 'https://github.com/k-takata/minpac.git'
    dest: '/home/lance/.config/nvim/pack/minpac/opt/minpac'
  
- name: Install desktop environment packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - gnome-tweaks
