- include_role:
    name: common

- import_tasks: prereqs.yml

- include_role:
    name: workstation

- include_role:
    name: developer

- import_tasks: shell.yml
- import_tasks: dotfiles.yml
- import_tasks: playbooks/software/anki.yml
- import_tasks: playbooks/software/pdfreader.yml
- import_tasks: playbooks/software/starship.yml
