- include_role:
    name: common

- import_tasks: prereqs.yml

- include_role:
    name: workstation

- include_role:
    name: developer

- import_tasks: shell.yml
- import_tasks: dotfiles.yml
- import_tasks: playbooks/software/anki.yml
- import_tasks: playbooks/software/neovim.yml
- import_tasks: playbooks/software/pdfreader.yml
- import_tasks: playbooks/software/starship.yml

- name: tmux > install tmux plugin manager
  become_user: lance
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/lance/.tmux/plugins/tpm
    clone: yes
    force: no

- name: chromium
  become: yes
  ansible.builtin.dnf:
    name: chromium
    state: latest
