- name: debugging playbook location
  debug:
    msg: "hello from playbooks/software"

- name: universal-ctags -> remove exuberant ctags
  become: yes
  ansible.builtin.dnf:
    name: ctags
    state: absent

- name: universal-ctags -> add GPG key for repository
  become: yes
  ansible.builtin.rpm_key:
    key: https://download.copr.fedorainfracloud.org/results/thindil/universal-ctags/pubkey.gpg
    state: present

- name: universal-ctags -> add repository
  become: yes
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:thindil:universal-ctags
    description: 'Copr repo for universal-ctags owned by thindil'
    baseurl: https://download.copr.fedorainfracloud.org/results/thindil/universal-ctags/fedora-rawhide-$basearch/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.copr.fedorainfracloud.org/results/thindil/universal-ctags/pubkey.gpg
    state: present

- name: universal-ctags -> install package
  become: yes
  ansible.builtin.dnf:
    name: universal-ctags
    state: latest