- name: neovim - install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - neovim
    - python3-neovim
  when: ansible_distribution == "Fedora"

- name: neovim - install packages
  homebrew:
    name: neovim
    state: latest
  when: ansible_distribution == "MacOSX"

# - name: neovim - prep minpac
#   ansible.builtin.file:
#     path: "${HOME}/.config/nvim/pack/minpac/opt"
#     state: directory
#     owner: lance
#     group: lance
#     mode: 0700

- name: neovim - install minpac
  become: yes 
  ansible.builtin.git:
    repo: https://github.com/k-takata/minpac.git
    dest: "${HOME}/.config/nvim/pack/minpac/opt/minpac"

# TODO: Look up how to run vim commands wo being in vim from the thoughtbot mac script
