- name: sublime-text
  block:
    - name: sublime-text > gpg key
      become: yes
      ansible.builtin.rpm_key:
        key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
        state: present

    - name: sublime-text > repository
      become: yes
      shell: "dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo"

    - name: sublime-text > package
      become: yes
      ansible.builtin.dnf:
        name: sublime-text
        state: latest
  when: ansible_distribution == "Fedora"
